<?php
namespace execut\import\bootstrap;


use execut\import\Module;
use execut\yii\Bootstrap;
use yii\i18n\PhpMessageSource;

class Common extends Bootstrap
{
    protected $_defaultDepends = [
        'modules' => [
            'import' => [
                'class' => Module::class,
            ],
        ],
    ];

    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub
        $this->initI18n();
    }

    public function initI18n() {
        \yii::$app->i18n->translations['execut/import'] = [
            'class' => PhpMessageSource::class,
            'sourceLanguage' => 'en',
            'basePath' => '@vendor/execut/yii2-import/messages',
            'fileMap' => [
                'execut/import' => 'import.php',
            ],
        ];
    }
}