<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 7/31/17
 * Time: 3:28 PM
 */

namespace execut\import\bootstrap;
use execut\import\Module;
use execut\yii\Bootstrap as BaseBootstrap;
use yii\mutex\FileMutex;

class Console extends BaseBootstrap
{
    protected $_defaultDepends = [
        'components' => [
            'mutex' => [
                'class' => FileMutex::class,
            ],
        ],
        'modules' => [
            'import' => [
                'class' => Module::class,
            ],
        ],
    ];

    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub
        if (empty($app->controllerMap['import'])) {
            $app->controllerMap['import'] = [
                'class' => \execut\import\controllers\ConsoleController::class,
            ];
        }
    }
}