<?php
/**
 * Date: 12.07.16
 * Time: 14:47
 */

namespace execut\import\controllers;


use execut\crud\params\Crud;
use execut\import\components\WebController;
use execut\import\models\Setting;
use execut\navigation\behaviors\Navigation;
use yii\helpers\ArrayHelper;

class SettingsController extends WebController
{
    public function actions()
    {
        $crud = new Crud([
            'modelClass' => Setting::class,
            'module' => 'import',
            'moduleName' => 'Import',
            'modelName' => Setting::MODEL_NAME,
        ]);

        return ArrayHelper::merge($crud->actions(), [
            'update' => [
                'adapter' => [
//                    'relationAdapterConfig' => [
//                        'schedulerEvents' => [
//                            'class' => Schedule::className(),
//                            'urlAttribute' => 'import_setting_id',
//                        ],
//                        'importSettingsSheets' => [],
//                    ],
//                    'relations' => [
//                        'schedulerEvents',
//                        'importSettingsSheets',
//                    ],
                ],
            ],
        ], parent::actions()); // TODO: Change the autogenerated stub
    }
}