<?php
/**
 * Date: 12.07.16
 * Time: 14:47
 */

namespace execut\import\controllers;


use execut\import\models\forms\Dictionaries;
use execut\import\models\forms\ImportSettingsSheets;
use execut\actions\Action;
use execut\actions\action\adapter\Delete;
use execut\actions\action\adapter\Edit;
use execut\actions\action\adapter\viewRenderer\DynaGrid;
use execut\navigation\behaviors\Navigation;
use \execut\actions\action\adapter\GridView;
class SettingsSheetsController extends SettingsController
{
    protected function getPages($idAttribute = 'id')
    {
        $modelClass = self::getModelClass();

        $pages = parent::getPages('import_setting_id'); // TODO: Change the autogenerated stub
        if ($page = $this->getModelPage($idAttribute, $modelClass)) {
            $pages[] = $page;
        }

        return $pages;
    }

    public function actions()
    {
        $modelClass = self::getModelClass();
        $modelLabel = 'Import settings sheets';
        \yii::$app->navigation->addPages($this->getPages());

        $ucfirstTitle = strtolower($modelLabel);
        return [
            'index' => [
                'class' => Action::className(),
                'adapter' => [
                    'class' => \execut\actions\action\adapter\GridView::className(),
                    'model' => $modelClass,
                    'view' => [
                        'class' => DynaGrid::className(),
                        'title' => $ucfirstTitle,
                        'modelClass' => $modelClass,
                    ],
                ],
            ],
            'update' => [
                'class' => Action::className(),
                'adapter' => [
                    'class' => Edit::className(),
                    'modelClass' => $modelClass,
                    'additionalAttributes' => [
                        'import_setting_id'
                    ],
//                    'relations' => [
//                        'importSettingsSheets'
//                    ],
                ],
            ],
            'get-dictionaries' => [
                'class' => Action::className(),
                'adapter' => [
                    'class' => GridView::className(),
                    'model' => Dictionaries::className(),
                    'view' => null,
                ],
            ],
            'delete' => [
                'class' => Action::className(),
                'adapter' => [
                    'class' => Delete::className(),
                    'modelClass' => $modelClass,
                ]
            ],
        ];
    }

    /**
     * @return string
     */
    protected static function getModelClass()
    {
        $modelClass = ImportSettingsSheets::className();
        return $modelClass;
    }
}