<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 9/21/16
 * Time: 3:56 PM
 */

namespace execut\import\models\forms;


use yii\base\Component;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\Expression;

class ImportLogsGrouped extends ImportLogs
{
    public $logsCount = null;
    public function getDataProvider() {
        $dataProvider = parent::getDataProvider();
//        $dataProvider->keys = 'level';
        $q = $dataProvider->query;
        $q->select([
            'message',
            'category',
            'logsCount' => new Expression('count(category)'),
        ]);
        $q->groupBy([
            'message',
            'category',
        ]);
        $q->orderBy('logsCount DESC');
        return $dataProvider;
    }

    public function getTotalCount() {
        return new Expression('count(category)');
    }

    public static function getGridColumns()
    {
        return [
            'category',
            'message',
            'logsCount',
        ];
    }

    public function attributeLabels()
    {
        $labels = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $labels['logsCount'] = 'Количество';

        return $labels;
    }
}