<?php

namespace execut\import\models\forms;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "import_settings_values".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property string $type
 * @property string $column_nbr
 * @property string $format
 * @property string $value_string
 * @property string $value_option
 * @property string $import_settings_set_id
 *
 * @property \execut\import\models\SettingsSet $importSettingsSet
 */
class ImportSettingsValues extends \execut\import\models\SettingsValue
{
    public function rules()
    {
        $rules = parent::rules();
        self::unsetRule($rules, 'required', 'import_settings_set_id');

        return ArrayHelper::merge([
            [['type'], 'validateValuesFields'],
        ], $rules); // TODO: Change the autogenerated stub
    }

    public function validateValuesFields() {
        $variants = [
            'column_nbr',
            'value_option',
            'value_string'
        ];
        $notEmptyCount = 0;
        foreach ($variants as $variant) {
            if ($variant === 'column_nbr' && $this->$variant === '0' || !empty($this->$variant)) {
                $notEmptyCount++;
            }
        }

        if ($notEmptyCount != 1) {
            $this->addError('type', 'Enter one of fields: column nbr, text value or dictionary option for attribute value');
        }
    }
}
