<?php

namespace execut\import\models\forms;
use yii\helpers\ArrayHelper;
use kartik\detail\DetailView;
use kartik\grid\ActionColumn;
use kartik\widgets\Select2;
use unclead\multipleinput\MultipleInput;
use unclead\multipleinput\MultipleInputColumn;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\JsExpression;

/**
 * This is the model class for table "import_settings_sheets".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property integer $order
 * @property string $import_setting_id
 *
 * @property \execut\import\models\SettingsSet[] $importSettingsSets
 * @property \execut\import\models\Setting $importSetting
 */
class ImportSettingsSheets extends \execut\import\models\SettingsSheet
{
    public $sets = [];

    public function init() {
        parent::init();
        if (!$this->sets) {
            $this->sets[] = [
                'values' => [],
            ];
        }
    }

    public function afterFind() {
        parent::afterFind();
        if (!$this->importSettingsSets) {
        } else {
            $this->sets = [];
            foreach ($this->importSettingsSets as $set) {
                $setAttributes = $set->attributes;
                if (empty($setAttributes['values'])) {
                    $setAttributes['values'] = [];
                }

                $this->sets[] = $setAttributes;
            }
        }
    }

    public function rules()
    {
        return ArrayHelper::merge([
            [['sets'], 'required'],
            [['sets'], 'validateSets'],
        ], parent::rules()); // TODO: Change the autogenerated stub
    }

    public function validateSets($attribute) {
        foreach ($this->$attribute as $index => $value) {
            $settingsSet = new ImportSettingsSets();
            $settingsSet->attributes = $value;
            $settingsSet->importSettingsSheetForValidate = $this;
            if (!$settingsSet->validate()) {
                foreach ($settingsSet->errors as $valueAttribute => $error) {
                    if (strpos($valueAttribute, '[') === false) {
                        $valueAttribute = '[' . $valueAttribute . ']';
                    }

                    $key = $attribute . '[' . $index . ']' . $valueAttribute;
                    if (!is_array($error)) {
                        $error = [$error];
                    }

                    foreach ($error as $e) {
                        $this->addError($key, $e);
                    }
                }
            }
        }
    }

    public function getDataProvider() {
        $query = self::find();
        foreach ($this->attributes as $attribute => $value) {
            if ($value) {
                $query->andWhere([
                    $attribute => $value
                ]);
            }
        }

        return new ActiveDataProvider([
            'query' => $query,
        ]);
    }

    public function getGridColumns() {
        return [
            'id',
            'name',
            'created',
            'updated',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model) {
                    $params = ['id' => $model->id, 'import_setting_id' => $this->import_setting_id];
                    $params[0] = 'import-settings-sheets/' . $action;

                    return Url::toRoute($params);
                },
                'buttons' => [
//                    'view' => function () {},
//                    'delete' => function () {},
                ],
            ],
        ];
    }

    public function getFormFields()
    {
        $getDictionariesUrl = Url::to(['get-dictionaries']);
        $dictionaryOptions = ['' => ''];
        $types = ImportSettingsSheets::getDictionaries();
        foreach ($this->importSettingsSets as $set) {
            foreach ($set->importSettingsValues as $value) {
                $type = explode('.', $value->type)[0];
                if (!empty($types[$type]) && !empty($value->value_option)) {
                    if ($model = $types[$type]->byId($value->value_option)->one()) {
                        $dictionaryOptions[$model->id] = $model->name;
                    }
                }
            }
        }

        return [
            [
                'attribute' => 'id',
                'displayOnly' => true,
            ],
            [
                'attribute' => 'import_setting_id',
                'type' => DetailView::INPUT_HIDDEN,
                'labelColOptions' => [
                    'style' => 'display:none'
                ],
//                'hideIfEmpty' => true,
//                'displayOnly' => true,
            ],
            [
                'attribute' => 'name',
            ],
            [
                'attribute' => 'order',
                'options' => [
                    'placeholder' => 'Order',
                    'type' => 'number',
                    'min' => 0,
                    'max' => 10,
                ],
            ],
            [
                'attribute' => 'sets',
                'type' => DetailView::INPUT_WIDGET,
                'value' => function () {return;},
                'widgetOptions' => [
                    'class' => MultipleInput::className(),
                    'allowEmptyList'    => false,
                    'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
                    'columns' => [
                        [
                            'name' => 'type',
                            'type' => MultipleInputColumn::TYPE_DROPDOWN,
                            'items' => self::getAttributesSetsTypesList(),
                            'options' => [
                                'prompt' => 'Set type'
                            ],
//                            'enableError' => true,
                        ],
                        [
                            'title' => 'Attributes values',
                            'name' => 'values',
                            'type' => MultipleInput::className(),
                            'options' => [
                                'class' => MultipleInput::className(),
                                'allowEmptyList'    => false,
                                'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
                                'columns' => [
                                    [
                                        'name' => 'type',
                                        'type' => Select2::className(),
                                        'options' => [
                                            'data' => self::getAttributesValuesTypesList(),
                                            'options' => [
                                                'prompt' => 'Attribute type'
                                            ],
                                        ],
//                                        'enableError' => true,
                                    ],
                                    [
                                        'name' => 'column_nbr',
                                        'type' => MultipleInputColumn::TYPE_TEXT_INPUT,
                                        'options' => [
                                            'type' => 'number',
                                            'placeholder' => 'Column nbr',
                                            'min' => 0,
                                            'max' => 20,
                                        ],
//                                        'enableError' => true,
                                    ],
                                    [
                                        'name' => 'number_delimiter',
                                        'type' => MultipleInputColumn::TYPE_TEXT_INPUT,
                                        'options' => [
                                            'placeholder' => 'Number delimiter'
                                        ],
//                                        'enableError' => true,
                                    ],
                                    [
                                        'name' => 'value_string',
                                        'type' => MultipleInputColumn::TYPE_TEXT_INPUT,
                                        'options' => [
                                            'placeholder' => 'Text value'
                                        ],
//                                        'enableError' => true,
                                    ],
//                                    [
//                                        'name' => 'value_option',
//                                        'type' => MultipleInputColumn::TYPE_TEXT_INPUT,
//                                        'options' => [
//                                            'placeholder' => 'Number value'
//                                        ],
//                                        'enableError' => true,
//                                    ],
                                    [
                                        'name' => 'value_option',
                                        'type' => Select2::className(),
                                        'headerOptions' => [
                                            'style' => 'width: 200px',
                                        ],
                                        'options' => [
                                            'initValueText' => $dictionaryOptions,
                                            'options' => [
                                                'placeholder' => 'Dictionary'
                                            ],
                                            'pluginOptions' => [
                                                'allowClear' => true,
                                                'ajax' => [
                                                    'url' => $getDictionariesUrl,
                                                    'dataType' => 'json',
                                                    'data' => new JsExpression(<<<JS
function(params) {
    var currentType = $(this).parents('.multiple-input-list__item:first').find('.list-cell__type select').val();
    return {
        name: params.term,
        type: currentType
    };
}
JS
)
                                                ],
                                            ],
                                        ],
//                                        'enableError' => true,
                                    ],
//                                    [
//                                        'name' => 'value_option',
//                                        'type' => MultipleInputColumn::TYPE_TEXT_INPUT,
//                                        /*'type' => DepDrop::className(),
//                                        'options' => [
//                                            'pluginOptions'=>[
//                                                'depends'=>['importsettingssheets-sets-{multiple_index_importsettingssheets-sets}-type'],
//                                                'placeholder' => 'Select...',
//                                                'url' => Url::to(['/site/subcat'])
//                                            ],
//                                        ],
//                                        'enableError' => true,*/
//                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'attribute' => 'created',
                'displayOnly' => true,
            ],
            [
                'attribute' => 'updated',
                'displayOnly' => true,
            ],
        ];
    }

    public static function getAttributesSetsTypesList() {
        return \yii::$app->getModule('import')->getAttributesSetsTypesList();
    }

    public static function getAttributesValuesTypesList() {
        return \yii::$app->getModule('import')->getAttributesValuesTypesList();
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        foreach ($this->importSettingsSets as $settingsSet) {
            $settingsSet->delete();
        }

        foreach ($this->sets as $set) {
            $settingsSet = new ImportSettingsSets();
            $settingsSet->attributes = $set;
            $this->link('importSettingsSets', $settingsSet);
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImportSettingsSets()
    {
        return $this->hasMany(\execut\import\models\forms\ImportSettingsSets::className(), ['import_settings_sheet_id' => 'id'])->inverseOf('importSettingsSheet');
    }

    public function beforeDelete()
    {
        foreach ($this->importSettingsSets as $sheet) {
            $sheet->delete();
        }

        return parent::beforeDelete();
    }

    public function search() {
        return $this->getDataProvider();
    }
}
