<?php

namespace execut\import\models\forms;
use \yii\helpers\ArrayHelper;

/**
 * This is the model class for table "import_settings_sets".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property string $type
 * @property string $import_settings_sheet_id
 *
 * @property \execut\import\models\SettingsSheet $importSettingsSheet
 * @property \execut\import\models\SettingsValue[] $importSettingsValues
 */
class ImportSettingsSets extends \execut\import\models\SettingsSet
{
    public $importSettingsSheetForValidate = null;
    public $values = [
    ];

    public function afterFind() {
        parent::afterFind();
        foreach ($this->importSettingsValues as $set) {
            $this->values[] = $set->attributes;
        }
    }

    public function rules()
    {
        $rules = parent::rules();
        self::unsetRule($rules, 'required', 'import_settings_sheet_id');
        return ArrayHelper::merge([
            [['values'], 'required'],
            [['values'], 'validateValues'],
        ], $rules); // TODO: Change the autogenerated stub
    }

    public function validateValues($attribute) {
        $this->validateRequiredFields();
        foreach ($this->$attribute as $index => $value) {
            $settingsValues = new ImportSettingsValues();
            $settingsValues->attributes = $value;
            if (!$settingsValues->validate()) {
                foreach ($settingsValues->errors as $valueAttribute => $error) {
                    if (!is_array($error)) {
                        $error = [$error];
                    }

                    foreach ($error as $e) {
                        $this->addError('[' . $attribute . ']' . '[' . $index . '][' . $valueAttribute . ']', $e);
                    }
//                    $this->addError($key, $error);
                }
            }
        }
    }

    public function attributes()
    {
        $attributes = parent::attributes(); // TODO: Change the autogenerated stub
        $attributes[] = 'values';

        return $attributes;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $this->deleteRelated();

        foreach ($this->values as $set) {
            $settingsSet = new ImportSettingsValues();
            $settingsSet->attributes = $set;
            if (empty($settingsSet->number_delimiter)) {
                $settingsSet->number_delimiter = ',';
            }

            $this->link('importSettingsValues', $settingsSet);
        }
    }

    public function beforeDelete()
    {
        $this->deleteRelated();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImportSettingsValues()
    {
        return $this->hasMany(\execut\import\models\forms\ImportSettingsValues::className(), ['import_settings_set_id' => 'id'])->inverseOf('importSettingsSet');
    }

    /**
     * @return \execut\import\models\SettingsValue
     */
    protected function deleteRelated()
    {
        foreach ($this->importSettingsValues as $settingsSet) {
            $settingsSet->delete();
        }
    }

    protected function validateRequiredFields()
    {
        if (!empty($this->type)) {
            $requiredTypes = $this->getRequiredAttributesByTypes()[$this->type];
            foreach ($this->values as $attribute => $value) {
                if (!empty($value['type'])) {
                    if (($key = array_search($value['type'], $requiredTypes)) !== false) {
                        unset($requiredTypes[$key]);
                    }
                }
            }

            if (!empty($requiredTypes)) {
                $labels = ImportSettingsSheets::getAttributesValuesTypesList();
                $attributes = [];
                foreach ($requiredTypes as $type) {
                    $attributes[$type] = $labels[$type];
                }
                $this->addError('type', 'Attributes ' . implode(', ', $attributes) . ' is required');
            }
        }
    }

    public function getRequiredAttributesByTypes() {
        return \yii::$app->getModule('import')->getRequiredAttributesByTypes();
    }
}
