<?php

namespace execut\import\models;
use execut\crudFields\Behavior;
use execut\crudFields\BehaviorStub;
use execut\crudFields\ModelsHelperTrait;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class LogGrouped extends Log
{
    public $logsCount = null;
    public function search() {
        $dataProvider = parent::search();
//        $dataProvider->keys = 'level';
        $q = $dataProvider->query;
        $q->select([
            'message',
            'category',
            'logsCount' => new Expression('count(category)'),
        ]);
        $q->groupBy([
            'message',
            'category',
        ]);
        $q->orderBy('logsCount DESC');
        return $dataProvider;
    }

    public function getTotalCount() {
        return new Expression('count(category)');
    }

    public static function getGridColumns()
    {
        return [
            'category',
            'message',
            'logsCount',
        ];
    }

    public function attributeLabels()
    {
        $labels = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $labels['logsCount'] = 'Количество';

        return $labels;
    }
}
