<?php

namespace execut\import\models;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "import_settings_sets".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property string $type
 * @property string $import_settings_sheet_id
 *
 * @property \execut\import\models\SettingsSheet $importSettingsSheet
 * @property \execut\import\models\SettingsValue[] $importSettingsValues
 */
class SettingsSet extends base\SettingsSet
{
    public $importSettingsSets = [
        'importSettingsSets' => [],
    ];

    public function delete()
    {
        foreach ($this->importSettingsValues as $value) {
            $value->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
