<?php

namespace execut\import\models;

use execut\crudFields\Behavior;
use execut\crudFields\BehaviorStub;
use execut\crudFields\fields\Boolean;
use execut\crudFields\fields\DropDown;
use execut\crudFields\fields\Email;
use execut\crudFields\fields\Group;
use execut\crudFields\fields\HasManyMultipleInput;
use execut\crudFields\fields\NumberField;
use execut\crudFields\fields\reloader\Reloader;
use execut\crudFields\fields\reloader\Target;
use execut\crudFields\fields\reloader\type\Dependent;
use execut\crudFields\ModelsHelperTrait;
use execut\import\components\Source;
use kartik\detail\DetailView;
use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * This is the model class for table "import_settings".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property integer $ignored_lines
 * @property string $email
 * @property string $email_title_match
 * @property string $csv_delimiter
 * @property string $csv_enclosure
 * @property string $import_files_source_id
 *
 * @property \execut\import\models\File[] $importFiles
 * @property \execut\import\models\FilesSource $importFilesSource
 * @property \execut\import\models\SettingsSheet[] $importSettingsSheets
 */
class Setting extends ActiveRecord
{
    use ModelsHelperTrait, BehaviorStub;
    const MODEL_NAME = '{n,plural,=0{Setting} =1{Setting} other{Settings}}';

    public function rules()
    {
        return $this->getBehavior('fields')->rules();
    }

    public static function find()
    {
        return new queries\Setting(static::class);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'import_settings';
    }

    public function getSource() {
        $adapter = $this->filesSource->getAdapterForSetting($this);
        $source = new Source([
            'adapter' => $adapter,
        ]);

        return $source;
    }

    public function load($data, $formName = null)
    {
        $result = parent::load($data, $formName); // TODO: Change the autogenerated stub
        $groupsVsTypes = [
            FilesSource::TYPE_EMAIL => [
                'emailGroup',
                'email',
                'email_title_match',
                'email_attachment_template'
            ],
            FilesSource::TYPE_FTP => [
                'ftpGroup',
                'ftp_host',
                'ftp_ssl',
                'ftp_port',
                'ftp_timeout',
                'ftp_login',
                'ftp_password',
                'ftp_dir',
                'ftp_file_name',
            ],
            FilesSource::TYPE_SITE => [
                'siteSettingsGroup',
                'site_host',
                'site_auth_url',
                'site_auth_method',
                'site_login_field',
                'site_password_field',
                'site_other_fields',
                'site_login',
                'site_password',
                'site_file_url',
            ],
        ];
        foreach ($groupsVsTypes as $typeKey => $groupFields) {
            if (!$this->isKeyOfFileSource($typeKey)) {
                foreach ($groupFields as $groupFieldName) {
                    /**
                     * @var Group $emailGroup
                     */
                    $this->getField($groupFieldName)
                        ->getDetailViewField()
                        ->hide();
                }
            }
        }

        return $result;
    }

    public function isKeyOfFileSource($key) {
        if (!$this->import_files_source_id) {
            return false;
        }

        return (int) $this->import_files_source_id == FilesSource::getIdByKey($key);
    }

    public function behaviors()
    {
        $filesSource = new DropDown([
            'attribute' => 'import_files_source_id',
            'relation' => 'filesSource',
            'required' => true,
        ]);
        $standardFields = $this->getStandardFields(['visible'], [
            'ignored_lines' => [
                'class' => NumberField::class,
                'attribute' => 'ignored_lines',
                'required' => true,
            ],
            'is_check_mime_type' => [
                'class' => Boolean::class,
                'attribute' => 'is_check_mime_type',
            ],
            'import_files_source_id' => $filesSource,
            'import_files_encoding_id' => [
                'class' => DropDown::class,
                'attribute' => 'import_files_encoding_id',
                'relation' => 'filesEncoding',
                'required' => true,
            ],
        ]);


        $emailTarget = new Target($filesSource);
//        $emailTarget->setValues([
//            function () {
//                return FilesSource::getIdByKey(FilesSource::TYPE_EMAIL);
//            }
//        ]);

        $reloader = new Reloader(new Dependent(), [$emailTarget]);
        $emailGroup = new Group([
            'label' => 'Настройки Email',
            'reloaders' => [$reloader],
            'name' => 'emailGroup',
        ]);

        $standardFields = ArrayHelper::merge($standardFields, [
            'emailGroup' => $emailGroup,
            'email' => [
                'class' => Email::class,
                'attribute' => 'email',
                'reloaders' => [$reloader],
            ],
            'email_title_match' => [
                'attribute' => 'email_title_match',
                'reloaders' => [$reloader],
            ],
            'email_attachment_template' => [
                'attribute' => 'email_attachment_template',
                'reloaders' => [$reloader],
            ],
        ]);

        $standardFields = ArrayHelper::merge($standardFields, [
            'csvGroup' => [
                'class' => Group::class,
                'label' => 'Настройки Csv',
                'reloaders' => [$reloader],
                'name' => 'csvGroup',
            ],
            'csv_delimiter' => [
                'attribute' => 'csv_delimiter',
                'reloaders' => [$reloader],
            ],
            'csv_enclosure' => [
                'attribute' => 'csv_enclosure',
                'reloaders' => [$reloader],
            ],
            'ftpGroup' => [
                'class' => Group::class,
                'label' => 'Настройки FTP',
                'reloaders' => [$reloader],
                'name' => 'ftpGroup',
            ],
            'ftp_host' => [
                'attribute' => 'ftp_host',
                'reloaders' => [$reloader],
            ],
            'ftp_ssl' => [
                'class' => Boolean::class,
                'attribute' => 'ftp_ssl',
                'defaultValue' => false,
                'reloaders' => [$reloader],
            ],
            'ftp_port' => [
                'attribute' => 'ftp_port',
                'reloaders' => [$reloader],
            ],
            'ftp_timeout' => [
                'attribute' => 'ftp_timeout',
                'reloaders' => [$reloader],
            ],
            'ftp_login' => [
                'attribute' => 'ftp_login',
                'reloaders' => [$reloader],
            ],
            'ftp_password' => [
                'attribute' => 'ftp_password',
                'reloaders' => [$reloader],
            ],
            'ftp_dir' => [
                'attribute' => 'ftp_dir',
                'reloaders' => [$reloader],
            ],
            'ftp_file_name' => [
                'attribute' => 'ftp_file_name',
                'reloaders' => [$reloader],
            ],
            'siteSettingsGroup' => [
                'class' => Group::class,
                'label' => 'Настройки Сайта',
                'name' => 'siteSettingsGroup',
                'reloaders' => [$reloader],
            ],
            'site_host' => [
                'attribute' => 'site_host',
                'reloaders' => [$reloader],
            ],
            'site_auth_url' => [
                'attribute' => 'site_auth_url',
                'reloaders' => [$reloader],
            ],
            'site_auth_method' => [
                'attribute' => 'site_auth_method',
                'reloaders' => [$reloader],
            ],
            'site_login_field' => [
                'attribute' => 'site_login_field',
                'reloaders' => [$reloader],
            ],
            'site_password_field' => [
                'attribute' => 'site_password_field',
                'reloaders' => [$reloader],
            ],
            'site_other_fields' => [
                'attribute' => 'site_other_fields',
                'reloaders' => [$reloader],
            ],
            'site_login' => [
                'attribute' => 'site_login',
                'reloaders' => [$reloader],
            ],
            'site_password' => [
                'attribute' => 'site_password',
                'reloaders' => [$reloader],
            ],
            'site_file_url' => [
                'attribute' => 'site_file_url',
                'reloaders' => [$reloader],
            ],
            'sheetsGroup' => [
                'class' => Group::class,
                'label' => 'Листы',
            ],
            'settingsSheets' => [
                'class' => HasManyMultipleInput::class,
                'attribute' => 'settingsSheets',
                'relation' => 'settingsSheets',
                'column' => false,
            ],
        ]);

        return [
            'relationsSaver' => [
                'class' => SaveRelationsBehavior::class,
                'relations' => [
                    'settingsSheets'
                ],
            ],
            'fields' => [
                'class' => Behavior::class,
                'module' => 'import',
                'fields' => $standardFields,
                'plugins' => \yii::$app->getModule('import')->getSettingsCrudFieldsPlugins(),
            ],
            'date' => [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public static function getFilesSourcesList() {
        return ArrayHelper::map(FilesSource::find()->all(), 'id', 'name');
    }

    public function getSiteOtherFields() {
        if (!empty($this->site_other_fields)) {
            return Json::decode($this->site_other_fields);
        }
    }

    public function delete()
    {
        foreach ($this->importSettingsVsSchedulerEvents as $event) {
            $event->delete();
        }

        foreach ($this->settingsSheets as $sheet) {
            $sheet->delete();
        }

        foreach ($this->files as $sheet) {
            $sheet->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return '#' . $this->id . ' ' . $this->name;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFiles()
    {
        return $this->hasMany(\execut\import\models\File::class, ['import_setting_id' => 'id'])->inverseOf('importSetting');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFilesEncoding()
    {
        return $this->hasOne(\execut\import\models\FilesEncoding::class, ['id' => 'import_files_encoding_id'])->inverseOf('settings');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFilesSource()
    {
        return $this->hasOne(\execut\import\models\FilesSource::class, ['id' => 'import_files_source_id'])->inverseOf('settings');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSettingsSheets()
    {
        return $this->hasMany(\execut\import\models\SettingsSheet::class, ['import_setting_id' => 'id'])->inverseOf('setting');
    }
}
